spring.application.name=rooftop
# Puerto del servidor
server.port=8080

# Conexión a PostgreSQL local
spring.datasource.url=jdbc:postgresql://localhost:5432/kaislo_rooftop
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate (El ORM) - update crea/actualiza las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect